In [1]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [36]:
from collections import defaultdict
import numpy as np

word_ls = []
for i in range(len(docs)):
  word_ls.extend(docs[i].split())
word_ls

['오늘',
 '동물원에서',
 '원숭이를',
 '봤어',
 '오늘',
 '동물원에서',
 '코끼리를',
 '봤어',
 '봤어',
 '동물원에서',
 '원숭이에게',
 '바나나를',
 '줬어',
 '바나나를']

In [41]:
word_dict = {}
index = 0
for word in word_ls:
  if word not in word_dict.keys():
    word_dict[word] = index
    index += 1
word_dict

{'동물원에서': 1,
 '바나나를': 6,
 '봤어': 3,
 '오늘': 0,
 '원숭이를': 2,
 '원숭이에게': 5,
 '줬어': 7,
 '코끼리를': 4}

In [45]:
from collections import defaultdict

word2index = defaultdict(lambda : len(word2index))
for word in word_ls:
  word2index[word]

In [46]:
word2index

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [48]:
unique_word_size = len(word2index)
one_hot_vectors = np.zeros((len(word_ls),unique_word_size)) #2차원
one_hot_vectors

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
for i, word in enumerate(word_ls):
  index = word2index[word] #우리가 만든 dict형태에서 찾는다
  one_hot_vectors[i, index] = 1 # onehot에서 1인 것을 찾아넣어주는 것

one_hot_vectors

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [55]:
np.sum(one_hot_vectors,axis=0)

array([2., 3., 1., 3., 1., 1., 2., 1.])

In [78]:
doc1 = '오늘 동물원에서 코끼리를 봤어 '
doc2 = '오늘 동물원에서 원숭이에게 사과를 줬어 '

word_ls1 = doc1.split()

one_hot_vectors1 = np.zeros((len(word_ls1),len(word_ls1))) #2차원

for i, word in enumerate(word_ls1):
  if word in word2index.keys():
    one_hot_vectors1[i, word_ls1.index(word)] = 1 # onehot에서 1인 것을 찾아넣어주는 것

one_hot_vectors1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
word2index

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

### 강사님 버전

In [79]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [80]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [81]:
doc_ls = []
for doc in docs:
  doc_ls.append(doc.split())
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [82]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

# [word2id[token] for doc in doc_ls for token in doc] -> 아래랑 같은 것
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [85]:
import numpy as np

BoW_ls = []
for i, doc in enumerate(doc_ls):
  bow = np.zeros(len(word2id),dtype=int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow)

In [86]:
BoW_ls

[array([1, 1, 1, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 2, 1, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 1, 2, 1])]

In [93]:
from IPython.core import display as ICD
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
for i in range(len(docs)):
  print("문서 {} : {}".format(i, docs))
  ICD.display([pd.DataFrame([BoW_ls[i]],columns=vocab)])
  print("\n\n")

문서 0 : ['오늘 동물원에서 원숭이를 봤어', '오늘 동물원에서 코끼리를 봤어 봤어', '동물원에서 원숭이에게 바나나를 줬어 바나나를']


[   오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
 0   1      1     1   1     0      0     0   0]




문서 1 : ['오늘 동물원에서 원숭이를 봤어', '오늘 동물원에서 코끼리를 봤어 봤어', '동물원에서 원숭이에게 바나나를 줬어 바나나를']


[   오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
 0   1      1     0   2     1      0     0   0]




문서 2 : ['오늘 동물원에서 원숭이를 봤어', '오늘 동물원에서 코끼리를 봤어 봤어', '동물원에서 원숭이에게 바나나를 줬어 바나나를']


[   오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
 0   0      1     0   0     0      1     2   1]